apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-connect-restore.fullname" . }}
  labels:
    {{- include "kafka-connect-restore.labels" . | nindent 4 }}
data:
  config.json: |
{{ .Values.restoreConfig  | indent 4 }}