apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-connect-sink.fullname" . }}
  labels:
    {{- include "kafka-connect-sink.labels" . | nindent 4 }}
data:
  config.json: |
{{ .Values.sinkConfig  | indent 4 }}